### ISSUE TITLE
Comment gérer les citations pour les notes des auditeurs

### ISSUE THREAD

**Issue by emmanuelbernard** [lescastcodeurs/lcc-slack-bot#38]
Dans l'episode news 281, on a mis 

De la part de Youen:

> Hello,
Cette année Codeurs en Seine, c’est le 17 novembre et le cfp est ouvert : https://cfp.codeursenseine.com/
N’hésitez pas à amener un peu de JVM dans l’appel à orateur. (ca commence à se faire rare).
Pour rappel : codeurs en seine c’est 1000 personnes autour des métiers du développement dans une des plus grande salle de Rouen, le kindarena.

qui a été rendu en 

```
De la part de Youen: > Hello, > > Cette année Codeurs en Seine, c’est le 17 novembre et le cfp est ouvert : https://cfp.codeursenseine.com/ > N’hésitez pas à amener un peu de JVM dans l’appel à orateur. (ca commence à se faire rare). > Pour rappel : codeurs en seine c’est 1000 personnes autour des métiers du développement dans une des plus grande salle de Rouen, le kindarena.
```
(une seule ligne).

A voir comment améliorer le rendu

**Comment by marcwrobel** [comment]
Les retours chariots dans un message ne sont pas conservés : ça permet d'avoir des listes "cohérentes". C'est la cause de ce bug.

Par contre je ne pense pas que ce soit utile pour le premier message du thread. Donc si on modifie le bot dans ce sens normalement le rendu devrait être correct.

**Comment by marcwrobel** [comment]
C'était bien ça. Il faut en plus dés-échappés les chevrons pour qu'ils soient correctement interprétés en markdown (dans le message Slack ils sont HTML-encodés : `&gt;` et `&lt;`)
