### ISSUE TITLE
Ajouter command @lcc tag

### ISSUE THREAD

**Issue by emmanuelbernard** [lescastcodeurs/lcc-slack-bot#39]
@lcc tag libellé label category

Affiche seulement les categories possibles de manière la plus suyccinte possible. C'est important parce que ca risque d'etre la commande la plus utile au quotidien

**Comment by marcwrobel** [comment]
@emmanuelbernard, il vaudrait mieux ne pas avoir la liste à deux endroits. Ça te va si je modifie aussi l'aide pour faire référence à cette nouvelle commande à la place de la liste de catégorie ?

**Comment by marcwrobel** [comment]
C'est fait, le résultat est le suivant :

`@lcc help` :
> Voici les commandes auxquelles je peux répondre (la ponctuation, les accents, la casse ainsi que la présence de mots supplémentaires sont ignorés).
> present | there (@lcc, es-tu présent ?, @lcc, are you there?) : permet de vérifier que je suis à l'écoute.aide | help (@lcc, à l'aide !, @lcc, help me please !) : affiche l'aide.
> category | categorie (@lcc, montre-moi les catégories., @lcc, show me the categories.) : affiche la liste des catégories avec leurs libellés associés.
> genere | generate (@lcc, génère les show notes., @lcc, generate show notes.) : génère les notes de l'épisode à partir des messages de ce channel et publie le résultat sur GitHub. Les show notes peuvent être publiées plusieurs fois: le fichier markdown est alors mis à jour. À noter :
> • Un channel Slack doit être dédié à un seul épisode.
> • Un thread de messages est reporté dans les show notes si son premier message contient au moins un lien.
> • Les réponses aux liens peuvent être de simples phrases comme des listes.
> • La formatage suivant est conservé : gras, italique, barré, code.
> • Les liens peuvent être catégorisés à l'aide de libellés (ex. https://www.google.com/ (outillage)). Les catégories, avec les libellés qu'il est possible d'utiliser, sont visibles grâce à la commande dédiée (@lcc, affiche les catégories.).

`@lcc categories` :
> Les catégories, et leurs libellés associés, sont : architecture (arch, archi, architecture, architectures), rubrique débutant (beginner, beginners, debutant, debutants), cloud (cloud), conférences (conf, conference, conferences), data (data), infrastructure (infra, infrastructure), langages (lang, langage, langages, langs, language, languages), librairies (lib, librairie, librairies, libraries, library, libs), méthodologies (methode, methodo, methodologie, methodologies, methodology), non catégorisées (news, nouvelle, nouvelles), sécurité (sec, secu, secure, securite, security), loi, société et organisation (law, loi, org, orga, organisation, organization, societe, society), outillage (outillage, tooling), outils de l’épisode (outil, outils, tool, tools), web (web)

Dis-moi si tu veux apporter des modifications.

**Comment by emmanuelbernard** [comment]
Pas de soucis pour faire une reference dans la commande help.
J'ai du mal a voir le rendu tant que tu n'as pas déployé le bot, ca sera sur une seule ligne ? Du coup je me dis que ma demande de rendu succint rend ca peu lisible potentiellement.
Aussi je trouvais ça bien l'ordre tel que défini dans le template et avec `non categorisé` au début.

Tu peux éventuellement déployer une version avec les deux formats (ancient et compact) et qu'on juge sur place?

**Comment by marcwrobel** [comment]
Oui, sur une seule ligne.

J'ai effectivement trié les catégories et les libellés par ordre alphabétique : je trouve que généralement, quand on cherche quelque chose, c'est plus simple quand c'est ordonné.

Ok, je vais faire deux commandes pour que tu puisses comparer.

**Comment by emmanuelbernard** [comment]
> J'ai effectivement trié les catégories et les libellés par ordre alphabétique : je trouve que généralement, quand on cherche quelque chose, c'est plus simple quand c'est ordonné. Par contre j'aurais dû ordonner les catégories par leur libellé et pas par le nom des entrées d'enum.

Mon raisonnement c'est que les cast codeurs connaissent generalement visuellement où se trouve la categorie qu'ils cherchent (vers les début car bas niveau, vers la fin car "soft skills") et donc l'ordre permet d'y arriver plus vite.

**Comment by marcwrobel** [comment]
Les deux résultats :
![Screenshot from 2022-08-25 11-16-37](https://user-images.githubusercontent.com/2988912/186626669-f97371e6-85e2-4d94-9694-e1007798e1a4.png)

Plus qu'a faire un choix (ou éventuellement mixer les deux ?).

**Comment by emmanuelbernard** [comment]
OK le premier est plus efficace.

Je propose aussi de mettre en avant un libellé par défaut

Example d'usage: Nouveau JEP <https://www.java.com> _(lang)_

Liste les catégories et leurs libellés:

* Langages: `lang` (`langage`, `langages`, `langs`, `language`, `languages`)
* Librairies: `lib` (...)
* Infrastructure: `infra` (...)
* Cloud: `cloud`
* Data: `data`
* Outillage: `outil` (`outillage`, `tooling`)
* Architecture: `archi` (...)
* Méthodologies: `methodo` (...)
* Sécurité: `secu` (...)
* Loi, société et organisation: `loi` (...)
* Outils des l'épisode: `outil-ep` (`outil-episode`)
* Rubrique débutant: `debutant` (...)
* Conférences: `conf` (...)
* Non catégorisé: laissé sans catégorie (`news`, `nouvelle`, `nouvelles`)



A noter deux changements dans la liste:
1. non catégorisé à la fin
2. outil comme label de Outillage vu qu'il est plus utilisé que outil de l'episode.

PS: désolé de tous ces aller retours.

**Comment by marcwrobel** [comment]
Pas de soucis. Le résultat final :
![Screenshot from 2022-08-25 14-55-59](https://user-images.githubusercontent.com/2988912/186670639-cb90b466-6913-4095-9d87-3249388ff355.png)

L'exemple d'usage est dans l'aide, je ne l'ai donc pas remis dans le texte renvoyé par cette nouvelle commande.

J'ai revu les libellés, introduit la notion de libellé "principal", et ai déplacé "non catégorisé" à la fin. Par contre j'ai retiré l'affichage des libellés pour "non catégorisé". Au final tous les libellés inconnus finissent dans cette catégorie, donc ils n'ont pas vraiment d'utilité à proprement parler.

J'ai aussi fait en sorte d'avoir toujours au moins deux libellés : ça simplifie grandement le formatage de la liste.
