### ISSUE TITLE
Appels @lcc dans les fils de discussions ne sont pas filtrés

### ISSUE THREAD

**Issue by emmanuelbernard** [lescastcodeurs/lcc-slack-bot#40]
<img width="291" alt="Screenshot 2022-08-16 at 10 48 32" src="https://user-images.githubusercontent.com/300760/184838279-f48661bb-0faf-4e33-a75f-6420b8e0556c.png">

Génère

Un lien sur [Git Blame](https://michaelheap.com/git-ignore-rev/) (conf)

* comment eviter les refactoring qui polluent git blame
* Autre lien https://lescastcodeurs.com/ (architecture)
* <@U03NS2ZGEJ2> help

**Comment by marcwrobel** [comment]
En lien avec https://github.com/lescastcodeurs/lcc-slack-bot/issues/42#issuecomment-1226977109.

**Comment by marcwrobel** [comment]
Vu dans le cadre de https://github.com/lescastcodeurs/lcc-slack-bot/issues/42#issuecomment-1227004217 : il faut filtrer tous les messages qui font référence à au moins un utilisateur, et pas uniquement ceux mentionnant @lcc.
