### ISSUE TITLE
Permettre de rajouter une catégorie quand on n'est pas l'auteur du message

### ISSUE THREAD

**Issue by emmanuelbernard** [lescastcodeurs/lcc-slack-bot#41]
# Contexte 

Si une personne met un lien et ne categorise pas, une seconde personne ne peut pas catégoriser car slack ne laisse pas modifier les messages des autres.
Si un lien est mal catégorisé, c'est pareil.

# Besoin

Permettre de categoriser dans le fil de discussion ou de _remplacer_ la catégorie.

# Proposition de syntaxe

Polices de caractères pour la programmation
https://www.programmingfonts.org/#firacode
* [glaforge](https://app.slack.com/team/U1N24U4Q0)
  [il y a un mois](https://lescastcodeurs.slack.com/archives/C03P9N0KR5F/p1657380035532349?thread_ts=1657379998.848519&cid=C03P9N0KR5F)
J’aime bien Fira Code moi :visage_légèrement_souriant:
Ce site permet de choisir parmi 111 polices différentes, pour pouvoir les comparer et choisir celle qu’on préfère
[emmanuel](https://app.slack.com/team/U1N1QLBNY)
  [il y a 3 minutes](https://lescastcodeurs.slack.com/archives/C03P9N0KR5F/p1660639989206999?thread_ts=1657379998.848519&cid=C03P9N0KR5F)
(outillage)

**Comment by marcwrobel** [comment]
Le sujet me semble être en lien avec #42.
