### ISSUE TITLE
Offer a way to order some articles within a section

### ISSUE THREAD

**Issue by emmanuelbernard** [lescastcodeurs/lcc-slack-bot#68]
Some articles are related and flow better when in a certain order.
Some are on the same specific topic (e.g. `Leyden`), some on the general area (e.g. `kotlin`).
We tend to order them in the shownotes but the bot has no notion of ordering.

This is a generally hard UX problem. So finding the minimum viable solution would be best vs building something too complicated.

## Agreed

Find a deterministic algorithm so that for two given runs of `generate`, the articles come in the same order.
I understand that technically the Slack API might not guarantee order, but if it does in practice that's good for me.

## Proposition 1

Unless specified explicitly, articles are listed in the order they were pushed in the Slack channel

## Proposition 2

Define a set of reactions `lcc_1` to `lcc_9`.
For a given section, articles marked by `lcc_n` are ordered according to the value of `n`.
Articles without `lcc_n` reaction are listed after the ones with such reactions.

## Conclusions

With these simple rules, I hope we can get a working solution that's simple enough to use.

**Comment by marcwrobel** [comment]
The first proposition is already implemented. The messages are explicitly written in the show notes using a "chronological" order (order by the `ts` field, null last - `ts` is a unique, per-channel, timestamp - see also https://github.com/slackhq/slack-api-docs/issues/7#issuecomment-67913241).

**Comment by marcwrobel** [comment]
Done. I will also add a way to sort replies of an articles.
