### ISSUE TITLE
Ajouter les conférences via la source Aurélie Vache

### ISSUE THREAD

**Issue by emmanuelbernard** [lescastcodeurs/lcc-slack-bot#74]
Aurélie public les sources de conférences sur github https://github.com/scraly/developers-conferences-agenda

Ca serait bien de pouvoir integrer cette liste dans les notes de l'épisode automatiquement. Mais surement des regles de filtre. @aheritier tu mettrais quoi comme règles?

**Comment by aheritier** [comment]
A l'origine notre liste se concentrait sur les conférences en France avec de rares exceptions sur les devoxx non FR. Je ne pense pas que beaucoup de nos auditeurs aient la chance de voyager pour participer aux conférences. Ils cherchent du local.

**Comment by marcwrobel** [comment]
Ok, donc on garde les entrées `Devoxx` et `(France)` ? Doit-on inclure aussi JavaOne ?

Avec ces critères ça donne pour le mois d'octobre :
* 4-6: [Devoxx Morocco](https://devoxx.ma/) - Agadir (Morocco) <a href="https://dvma22.cfp.dev"><img alt="CFP Devoxx Morocco" src="https://img.shields.io/static/v1?label=CFP&message=6-Jun-2022%20to%2015-Jul-2022&color=red"> </a>
* 6-7: [Paris Web](https://paris-web.fr/) - Paris (France) <img alt="Closed Captions" src="https://img.shields.io/static/v1?label=CC&message=Closed%20Captions&color=blue" /> <a href="https://appel.paris-web.fr/"><img alt="CFP Paris Web" src="https://img.shields.io/static/v1?label=CFP&message=24-Mar-2022-%3E24-Apr-2022&color=red"> </a>
* 7: [DevFest Perros-Guirec](https://devfest.codedarmor.fr/) - Perros-Guirec (France)
* 7: [Hackvens](https://hackvens.fr/) - Rennes (France)
* 10-14: [Devoxx Belgium](https://devoxx.be/) - Antwerp (Belgium) <a href="[https://devoxx.be/](https://dvbe22.cfp.dev/#/login)"><img alt="CFP Devoxx Belgium 2022" src="https://img.shields.io/static/v1?label=CFP&message=Jun-2022%20to%2015-July-2022&color=red"> </a>
* 13-14: [Volcamp 2022](https://www.volcamp.io/) - Clermont Ferrand (France) <a href="https://conference-hall.io/public/event/8Wu147xoRDKQSjGcawoY"><img alt="CFP Volcamp" src="https://img.shields.io/static/v1?label=CFP&message=%3E13-May-2022&color=red"> </a>
* 16–20: [JavaOne](https://www.oracle.com/cloudworld/javaone/) - Las Vegas, Nevada (USA)
* 17: [Agile Tour Montpellier 2022](https://agiletourmontpellier.fr/2022/) - Montpellier (France)
* 18-19: [FlowCon](https://flowcon.fr/) - Montrouge (France)
* 20-21: [DevFest Nantes](https://devfest.gdgnantes.com/) - Nantes (France) <a href="https://conference-hall.io/public/event/CfucIjaXxrZThJE0POR3"> <img alt="Closed Captions" src="https://img.shields.io/static/v1?label=CC&message=Closed%20Captions&color=blue" /> <img alt="CFP Sunny Tech 2022" src="https://img.shields.io/static/v1?label=CFP&message=1-Apr-2022%20to%2019-Jun-2022&color=red"> </a>
* 20-21: [NixCon 2022](https://discourse.nixos.org/t/nixcon-2022-location-details-more/21392) - Paris (France)
* 27-28: [Agile Tour Bordeaux](http://agiletourbordeaux.fr/) - Bordeaux (France) <a href="https://sessionize.com/agile-tour-bordeaux-2022/"><img alt="CFP Agile Tour Bordeaux" src="https://img.shields.io/static/v1?label=CFP&message=until%2031-July-2022&color=red"> </a>

**Comment by aheritier** [comment]
Normalement la rubrique conférences couvre la France et pays limitrophes. En théorie plutôt les conférences francophones mais je ne sais pas si nous sommes beaucoup écoutés en dehors de la France.

**Comment by aheritier** [comment]
En tout cas @marcwrobel c'est déjà très bien comme ça (France + devoxx)

**Comment by marcwrobel** [comment]
J'ai une première version qui fonctionne, le résultat est visible sur https://github.com/marcwrobel/staging.lescastcodeurs.com/blob/main/test-42.md.

Contrairement à ce qui avait été fait à la main sur https://github.com/lescastcodeurs/lescastcodeurs.com/blob/main/_posts/2022-06-13-lcc-280-lecon-de-geographie.md je n'ai pas conservé l'affichage mois par mois : c'était plus simple à coder en modifiant les lignes qui nous intéressent pour y injecter la date complète (car pas besoin de supprimer les mois vide ou de regrouper les lignes de conférences mois par mois).

@aheritier , @emmanuelbernard , vous en pensez quoi ?

* Vous préférez tout de même que ce soit affiché mois par mois ?
* La petite phrase d'introduction vous va ?
* Faut-il filtrer les conférences trop lointaines (car là on affiche déjà 12-14 avril 2023 : [Devoxx France](https://www.devoxx.fr/) - Paris (France)) ?

**Comment by aheritier** [comment]
@marcwrobel je trouve ça très bien ainsi.
Pas besoin des mois.
La limite dans le temps on peut la faire à l'oral et les laisser dans les shownotes

**Comment by marcwrobel** [comment]
Ok, je merge ça du coup.

**Comment by marcwrobel** [comment]
Ah oui, j'oubliais, le nom du dépôt GitHub ainsi que la liste des chaînes de caractères utilisées pour extraire les conférences française est configurable (cf. README).
