### ISSUE TITLE
Support show notes generation of interview episodes

### ISSUE THREAD

**Issue by marcwrobel** [lescastcodeurs/lcc-slack-bot#85]
Currently lcc-slack-bot only support show notes generation of news episode. It could be useful to add support for show notes generation of interview episodes.

A few rules that may be used to develop this feature :

- `generate` command must be used.
- If the slack thread is named interview-xxx (xxx = episode number), [interviews template](https://github.com/lescastcodeurs/lescastcodeurs.com/wiki/Template-interview) is used for generating the show notes. Else the [news template](https://github.com/lescastcodeurs/lcc-slack-bot/blob/main/src/main/resources/templates/show-notes.md) is used.
- New categories must be added for the interviews template (Ta vie ton oeuvre, Introduction, La techno en concepts...). Those categories must be used exclusively in this template (and news template categories cannot be used for interviews template).

**Comment by marcwrobel** [comment]
Won't do : using slack for this type of show notes is far from optimal.

**Comment by emmanuelbernard** [comment]
Je ne vois pas de façons de faciliter aujourd'hui. A méditer.
